spring:
  datasource:
    price:
      url: jdbc:mysql://114.55.75.116:3306/order_center?useSSL=false&useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true&tinyInt1isBit=false
      username: root
      password: C#m9klT@n4!N3m
      driver-class-name: com.mysql.jdbc.Driver
      druid:
        min-idle: 1
        max-active: 300
        filter:
          stat:
            log-slow-sql: true
            slow-sql-millis: 50
        initial-size: 1
        max-wait: 60000
        validation-query: select 1
        test-while-idle: true